### PR TITLE
Simple check for shortcuts.vdf file

### PR DESCRIPTION
**Pull request by hartigan43**
added basic check for missing shortcuts.vdf, prints an explanation how to generate the file if on steamdeck

### CODE REVIEW

**Comment by hartigan43** [comment]
For reference, I was receiving a FileNotFound error for shortcuts.vdf, installing the chrome shortcut as prompted on the deck fixed it.  I had no shortcuts on my steamdeck or my desktop and no shortcuts.vdf file by default.

**Comment by redromnon** [comment]
I'm actually working on creating the shorcuts.vdf so that the user doesn't need to do anything like adding a Non-Steam game. I'll keep this PR open and come back to this again if I don't get the expected working.

**Comment by hartigan43** [comment]
Sounds good.  I had planned to look into the vdf creation as well, if you have already started it I don't need to follow up, but happy to help.

**Comment by redromnon** [comment]
I haven't started implementing yet since I'm a bit occupied. You can go ahead with the creation of the vdf file if you want to.

**Comment by redromnon** [comment]
I am closing this PR since I've implemented the creation of absent shortcuts.vdf files.

**Pull request closed without merging**
