### PR TITLE
Minor change to get finding the Heroic folder working.

### PR DESCRIPTION
**Pull request by Ross-Carran**
Added re (regular expression) import into file, changed conditional statement to search via regular expression.

### CODE REVIEW

**Comment by redromnon** [comment]
But doesn't it do exactly the same thing as "if in"?

**Comment by Ross-Carran** [comment]
You are right, I wouldv'e originaly tested it without the appimage of HeroicGameLauncher open, Ignore this Pull.

On another note, Noticed the batch files will need to be refreashed each time the HeroicGameLauncher appimage is closed then opened again, and that the Appimamage would have to be open for them to work at all, as it relies on the legendary executable that comes with HeroicGameLauncher in the AppImage.

Would it help if a flatpak or appimage of legendary was made?
Maybe more a flatpak it would give a more fixed locarion for the created batch files to work with.

**Comment by redromnon** [comment]
I've already [given an explanation](https://github.com/redromnon/HeroicBashLauncher/wiki/FAQ#why-are-my-games-not-launching-i-use-heroic-via-appimage) as to why Heroic should always be open when using AppImage and even suggested a solution. And yes, I'm waiting for Flatpak support to arrive.

**Comment by redromnon** [comment]
Closing pull request

**Pull request closed without merging**
